import { readFileSync, readdirSync, writeFileSync, existsSync } from 'fs'
import { join } from 'path'

const notesDir = 'e:/RedBook/02_collections/2_N_concepts/N_notes'
const files = readdirSync(notesDir).filter(f => f.endsWith('.md'))
console.log(`Total .md files: ${files.length}`)

// Known type patterns — use (?:^|(?<=[\s,，、/])) for left boundary and (?:$|(?=[\s,，、/])) for right
function inferTypeFromName(name) {
  const n = name.replace(/\.md$/, '')
  // Method/technique patterns — match Chinese characters without relying on \b
  const methodPatterns = ['法', '模型', '方法', '法则', '定律', '原理', '策略', '技巧', '算法', '公式', '流程', '框架', '模式', '系统', '工具', '步骤', 'SOP']
  for (const p of methodPatterns) {
    if (n.includes(p)) return '方法型'
  }
  // Mechanism patterns
  const mechanismPatterns = ['效应', '机制', '陷阱', '悖论', '困境', '瓶颈', '循环', '反馈', '动力', '博弈', '激励', '延迟', '边际', '均衡']
  for (const p of mechanismPatterns) {
    if (n.includes(p)) return '机制型'
  }
  // Scene patterns
  const scenePatterns = ['时刻', '场景', '处境', '阶段', '状态']
  for (const p of scenePatterns) {
    if (n.includes(p)) return '场景型'
  }
  // Evidence patterns
  const evidencePatterns = ['研究', '实验', '证据', '案例', '数据', '报告', '论文', '统计', '分析']
  for (const p of evidencePatterns) {
    if (n.includes(p)) return '证据型'
  }
  // Question patterns
  if (/^(如何|怎样|怎么|为什么|是否|要不要|该不该)/.test(n) || /\?$/.test(n)) return '问题型'
  const questionPatterns = ['问题', '疑问']
  for (const p of questionPatterns) {
    if (n.includes(p)) return '问题型'
  }
  // Translation/Meta patterns
  const translatePatterns = ['转译', '解读', '诠释', '翻译']
  for (const p of translatePatterns) {
    if (n.includes(p)) return '转译型'
  }
  // Expression patterns
  const exprPatterns = ['表达', '沟通', '对话', '叙事', '故事', '写作', '语言', '话语', '隐喻']
  for (const p of exprPatterns) {
    if (n.includes(p)) return '表达型'
  }
  // Prototype patterns
  const protoPatterns = ['原型', '人格', '角色', '类型', '特征', '画像']
  for (const p of protoPatterns) {
    if (n.includes(p)) return '母题型'
  }
  // Anti-pattern
  const antiPatterns = ['误区', '谬误', '幻觉', '偏见', '认知偏差', '反模式']
  for (const p of antiPatterns) {
    if (n.includes(p)) return '反模式型'
  }
  return null
}

const concepts = []
let parseCount = 0

for (const file of files) {
  let content
  try {
    content = readFileSync(join(notesDir, file), 'utf-8')
  } catch {
    continue
  }

  const name = file.replace(/\.md$/, '')

  // Extract type from content
  let type = ''
  const typeMatch = content.match(/N卡类型[：:]\s*([^\n]+)/)
  if (typeMatch) {
    type = typeMatch[1].replace(/`/g, '').replace(/\s+/g, ' ').trim()
    // Take the first type if multiple are listed (separated by /)
    const firstType = type.split(/[／/]/)[0].trim()
    type = firstType
  }

  // Extract maturity
  let maturity = ''
  const maturityMatch = content.match(/成熟度[：:]\s*`?(Seed|Growing|Evergreen)`?/)
  if (maturityMatch) {
    maturity = maturityMatch[1]
  }

  // If no type found, try to infer from filename
  if (!type) {
    const inferred = inferTypeFromName(file)
    if (inferred) {
      type = inferred
    }
  }

  // If maturity still not found, check for the far format (deeper in file)
  if (!maturity) {
    const matMatch2 = content.match(/成熟度[：:]\s*`(Seed|Growing|Evergreen)`/)
    if (matMatch2) {
      maturity = matMatch2[1]
    }
  }

  // Default to Seed if nothing found
  if (!maturity) {
    maturity = 'Seed'
  }

  // Default unknown types
  if (!type) {
    type = '概念型'
  }

  // Validate type against known types
  const validTypes = ['概念型', '母题型', '场景型', '机制型', '方法型', '转译型', '表达型', '证据型', '问题型', '反模式型', '需要型']
  if (!validTypes.includes(type)) {
    type = '概念型'
  }

  concepts.push({ name, type, maturity, file })
  parseCount++
}

console.log(`Parsed ${parseCount} concepts`)

// Count stats
const typeCounts = {}
const maturityCounts = {}
for (const c of concepts) {
  typeCounts[c.type] = (typeCounts[c.type] || 0) + 1
  maturityCounts[c.maturity] = (maturityCounts[c.maturity] || 0) + 1
}
console.log('Types:', typeCounts)
console.log('Maturities:', maturityCounts)

// Generate JS file content
const jsContent = `// Auto-generated by scanConcepts.mjs
// Total concepts: ${concepts.length}

export const conceptTypes = [
  { id: '概念型', label: '概念型', color: '#8a5a44' },
  { id: '母题型', label: '母题型', color: '#6b4c7a' },
  { id: '场景型', label: '场景型', color: '#a56a2a' },
  { id: '机制型', label: '机制型', color: '#204f67' },
  { id: '方法型', label: '方法型', color: '#5f7d43' },
  { id: '转译型', label: '转译型', color: '#2f6f73' },
  { id: '表达型', label: '表达型', color: '#795b9b' },
  { id: '证据型', label: '证据型', color: '#bf6f3f' },
  { id: '问题型', label: '问题型', color: '#a04040' },
  { id: '反模式型', label: '反模式型', color: '#994444' },
  { id: '需要型', label: '需要型', color: '#4a8a8a' },
]

export const maturityLevels = [
  { id: 'Seed', label: '种子' },
  { id: 'Growing', label: '成长中' },
  { id: 'Evergreen', label: '常青' },
]

export const concepts = [
${concepts.map(c => `  { name: ${JSON.stringify(c.name)}, type: ${JSON.stringify(c.type)}, maturity: ${JSON.stringify(c.maturity)}, file: ${JSON.stringify(c.file)} },`).join('\n')}
]
`

const outPath = 'e:/RedBook/04_operations/04_products_and_experiments/book-kb-multi/web/src/data/conceptIndexData.js'
writeFileSync(outPath, jsContent, 'utf-8')
console.log(`Written to ${outPath}`)
